# Generated by Django 4.1 on 2022-09-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=250)),
            ],
        ),
    ]
