# Generated by Django 4.1 on 2022-09-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
