# Generated by Django 4.1 on 2022-09-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
