# Generated by Django 4.1 on 2022-09-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_skill_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('instName', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('detail', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
