# Generated by Django 4.1 on 2022-09-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_education_end_alter_education_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='instName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
