# Generated by Django 4.1 on 2022-09-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='posts',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
