# Generated by Django 4.1 on 2022-09-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_category_status_portfolio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
