# Generated by Django 4.1 on 2022-09-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_portfolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('birthday', models.DateField()),
                ('website', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('Freelancer', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
