# Generated by Django 4.1 on 2022-09-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('detail', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
