# Generated by Django 4.1 on 2022-09-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_portfolio_end_portfolio_start_alter_experience_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/gallery')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.portfolio')),
            ],
        ),
    ]
